"""
generate_docs_index.py -- scans docs/*.md and builds docs/index.md,
grouped by tag. Does NOT generate doc content -- that's written by hand.
This only automates structure (the index) and enforcement (missing-doc
warnings).

Run manually after adding/editing a doc:
    python3 scripts/generate_docs_index.py
"""
import os
import re

DOCS_DIR = "/root/docs"
INDEX_FILE = os.path.join(DOCS_DIR, "index.md")

# Features expected to have a doc. Update this list by hand when a real
# feature is added or removed -- this is a deliberate human decision,
# not something inferred from the codebase.
EXPECTED_TOPICS = {
    "mealie": "Mealie meal planning",
    "streams": "Streams media player",
    "syncthing": "Syncthing devices",
    "config-and-setup": "Configuration & setup system",
    "nginx-and-networking": "nginx & networking",
    "system-panel": "System panel (status & factory reset)",
    "architecture-map": "Architecture map",
    "security": "Security",
}


def parse_doc(path):
    with open(path) as f:
        lines = f.readlines()

    tags = []
    title = os.path.basename(path)

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("tags:"):
            tags = [t.strip() for t in stripped[len("tags:"):].split(",") if t.strip()]
        elif stripped.startswith("# ") and title == os.path.basename(path):
            title = stripped[2:].strip()

    return {"path": path, "title": title, "tags": tags}


def build_index():
    doc_files = sorted(f for f in os.listdir(DOCS_DIR) if f.endswith(".md") and f != "index.md")
    docs = [parse_doc(os.path.join(DOCS_DIR, f)) for f in doc_files]

    by_tag = {}
    for doc in docs:
        for tag in doc["tags"]:
            by_tag.setdefault(tag, []).append(doc)

    lines = ["# Documentation Index", "", "_Generated by scripts/generate_docs_index.py -- do not edit by hand._", ""]

    for tag in sorted(by_tag.keys()):
        lines.append(f"## {tag}")
        lines.append("")
        for doc in by_tag[tag]:
            filename = os.path.basename(doc["path"])
            lines.append(f"- [{doc['title']}]({filename})")
        lines.append("")

    documented_slugs = {os.path.splitext(os.path.basename(d["path"]))[0] for d in docs}
    missing = [name for slug, name in EXPECTED_TOPICS.items() if slug not in documented_slugs]

    if missing:
        lines.append("## Missing documentation")
        lines.append("")
        lines.append("The following expected topics have no matching doc file:")
        lines.append("")
        for name in missing:
            lines.append(f"- {name}")
        lines.append("")

    with open(INDEX_FILE, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {INDEX_FILE} ({len(docs)} docs, {len(by_tag)} tags)")
    if missing:
        print(f"WARNING: {len(missing)} expected topic(s) missing documentation: {', '.join(missing)}")
    else:
        print("All expected topics are documented.")


if __name__ == "__main__":
    build_index()
