"""
reset_manager.py -- shared logic for first-time setup and factory reset.

Both real setup/reset and the dry-run simulator ("Fake Factory Reset") walk
the exact same list of actions below, so the simulator can never drift out
of sync with what a real run actually does. Each action logs a line
(returned as a list when return_log=True, for the dashboard's preview UI)
and always prints too, for CLI usage via setup.sh.
"""
import argparse
import os
import secrets as secrets_module
import shutil
import subprocess

ROOT = "/root"
ENV_FILE = os.path.join(ROOT, ".env")
ENV_EXAMPLE = os.path.join(ROOT, ".env.example")
JS_CONFIG_FILE = os.path.join(ROOT, "js", "config.js")
SYSTEMD_UNIT_PATH = "/etc/systemd/system/mealie-trigger.service"

SYSTEMD_UNIT_CONTENT = """[Unit]
Description=Mealie Meal Plan Trigger
After=network.target

[Service]
ExecStart=/usr/bin/python3 /root/scripts/trigger_server.py
Restart=always
WorkingDirectory=/root/scripts

[Install]
WantedBy=multi-user.target
"""

RESET_TARGETS = [
    "scripts/mealie_token.txt",
    "scripts/meal_history.json",
    "scripts/syncthing_config.json",
    "audiobooks/library.json",
    "audiobooks/profiles.json",
    "audiobooks/config.json",
    "audiobooks/local_progress.json",
    "audiobooks/local_shared.json",
    "audiobooks/state.json",
    "audiobooks/local_files",
    ".env",
]


def _log(log_lines, message):
    log_lines.append(message)
    print(message)


def _read_env_value(key, default=None):
    if not os.path.exists(ENV_FILE):
        return default
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if line.startswith(f"{key}="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return default


def read_current_host_ip():
    return _read_env_value("HOST_IP", "192.168.0.201")


def read_current_timezone():
    return _read_env_value("TIMEZONE", "UTC")


def generate_secret():
    return secrets_module.token_hex(24)


def write_env(host_ip, timezone, dry_run, log_lines):
    secret = generate_secret()
    pihole_pw = secrets_module.token_urlsafe(12)
    content = (
        f"HOST_IP={host_ip}\n"
        f"TIMEZONE={timezone}\n"
        f"TRIGGER_SECRET={secret}\n"
        f"PIHOLE_WEBPASSWORD={pihole_pw}\n"
        f"MEALIE_TOKEN_FILE=/root/scripts/mealie_token.txt\n"
    )
    if dry_run:
        _log(log_lines, f"[dry-run] would write {ENV_FILE} with a freshly generated "
                         f"TRIGGER_SECRET and PIHOLE_WEBPASSWORD (values hidden)")
        return
    with open(ENV_FILE, "w") as f:
        f.write(content)
    os.chmod(ENV_FILE, 0o600)
    _log(log_lines, f"Wrote {ENV_FILE}")


def write_js_config(host_ip, dry_run, log_lines):
    content = (
        "// config.js -- browser-side counterpart to scripts/config.py.\n"
        "// Generated by reset_manager.py during setup/reset -- do not hand-edit.\n"
        f"export const HOST_IP = '{host_ip}';\n"
    )
    if dry_run:
        _log(log_lines, f"[dry-run] would write {JS_CONFIG_FILE} with HOST_IP={host_ip}")
        return
    with open(JS_CONFIG_FILE, "w") as f:
        f.write(content)
    _log(log_lines, f"Wrote {JS_CONFIG_FILE}")


def install_systemd_service(dry_run, log_lines):
    if dry_run:
        _log(log_lines, f"[dry-run] would write {SYSTEMD_UNIT_PATH}, run "
                         f"'systemctl daemon-reload', and 'systemctl enable --now mealie-trigger.service'")
        return
    with open(SYSTEMD_UNIT_PATH, "w") as f:
        f.write(SYSTEMD_UNIT_CONTENT)
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "enable", "--now", "mealie-trigger.service"], check=True)
    _log(log_lines, f"Installed and started {SYSTEMD_UNIT_PATH}")


def remove_personal_data(dry_run, log_lines):
    for rel_path in RESET_TARGETS:
        full = os.path.join(ROOT, rel_path)
        exists = os.path.exists(full)
        if dry_run:
            state = "would delete" if exists else "would skip (not present)"
            _log(log_lines, f"[dry-run] {state}: {rel_path}")
            continue
        if not exists:
            continue
        if os.path.isdir(full):
            shutil.rmtree(full)
        else:
            os.remove(full)
        _log(log_lines, f"Removed {rel_path}")


def bring_up_stack(dry_run, log_lines):
    if dry_run:
        _log(log_lines, "[dry-run] would run: docker compose up -d --force-recreate")
        return
    subprocess.run(
        ["docker", "compose", "up", "-d", "--force-recreate"],
        cwd=ROOT, check=True,
    )
    _log(log_lines, "Ran: docker compose up -d --force-recreate")


def restart_trigger_service(dry_run, log_lines):
    if dry_run:
        _log(log_lines, "[dry-run] would run: systemctl restart mealie-trigger.service")
        return
    subprocess.run(
        ["systemctl", "restart", "mealie-trigger.service"], check=True,
    )
    _log(log_lines, "Ran: systemctl restart mealie-trigger.service")


def run_setup(host_ip, timezone, dry_run, skip_service_restart=False, return_log=False):
    log_lines = []
    _log(log_lines, f"{'[DRY RUN] ' if dry_run else ''}Setting up...")
    write_env(host_ip, timezone, dry_run, log_lines)
    write_js_config(host_ip, dry_run, log_lines)
    if skip_service_restart:
        _log(log_lines, "Skipping automatic service setup -- SSH in and finish manually.")
    else:
        install_systemd_service(dry_run, log_lines)
        bring_up_stack(dry_run, log_lines)
        restart_trigger_service(dry_run, log_lines)
    _log(log_lines, f"{'[DRY RUN] ' if dry_run else ''}Setup complete.")
    return log_lines if return_log else None


def run_reset(host_ip, timezone, dry_run, skip_service_restart=False, return_log=False):
    log_lines = []
    _log(log_lines, f"{'[DRY RUN] ' if dry_run else ''}Factory reset starting...")
    remove_personal_data(dry_run, log_lines)
    write_env(host_ip, timezone, dry_run, log_lines)
    write_js_config(host_ip, dry_run, log_lines)
    if skip_service_restart:
        _log(log_lines, "Skipping automatic service restart -- SSH in and run "
                         "'docker compose up -d --force-recreate' (or reboot) to finish.")
    else:
        bring_up_stack(dry_run, log_lines)
        restart_trigger_service(dry_run, log_lines)
    _log(log_lines, f"{'[DRY RUN] ' if dry_run else ''}Factory reset complete.")
    return log_lines if return_log else None


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Setup / factory reset for the dashboard system.")
    parser.add_argument("--reset", action="store_true", help="Factory reset instead of first-time setup")
    parser.add_argument("--dry-run", action="store_true", help="Simulate only, change nothing")
    parser.add_argument("--host-ip", required=True)
    parser.add_argument("--timezone", required=True)
    args = parser.parse_args()

    if args.reset:
        run_reset(args.host_ip, args.timezone, args.dry_run)
    else:
        run_setup(args.host_ip, args.timezone, args.dry_run)
